# Generated by Django 5.0 on 2024-01-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='students',
            field=models.ManyToManyField(blank=True, to='Collage.studentresultsheet'),
        ),
    ]
