# Generated by Django 5.0 on 2024-01-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collage', '0003_answersheet_result_sheet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresultsheet',
            name='stu_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
