# Generated by Django 5.0 on 2024-01-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collage', '0004_alter_studentresultsheet_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentresultsheet',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
