# Generated by Django 5.0 on 2024-01-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collage', '0005_alter_answersheet_code_alter_studentresultsheet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresultsheet',
            name='analytical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresultsheet',
            name='chemistry',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresultsheet',
            name='english',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresultsheet',
            name='math',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentresultsheet',
            name='physics',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
