# Generated by Django 5.0.1 on 2024-01-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collage', '0007_rename_batch_studentresultsheet_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresultsheet',
            name='analytical',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresultsheet',
            name='chemistry',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresultsheet',
            name='english',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresultsheet',
            name='math',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresultsheet',
            name='physics',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentresultsheet',
            name='result',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
