# Generated by Django 5.0.1 on 2024-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collage', '0008_alter_studentresultsheet_analytical_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresultsheet',
            name='matched_sheet',
            field=models.ImageField(blank=True, null=True, upload_to='student/'),
        ),
    ]
