# Generated by Django 5.0.1 on 2024-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collage', '0009_studentresultsheet_matched_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresultsheet',
            name='matched_sheet',
            field=models.TextField(blank=True, null=True),
        ),
    ]
